apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: go-app-argo-config
  namespace: argocd
spec:
  project: test-project
  source:
    repoURL: https://github.com/anandg7259/private_repo.git
    targetRevision: main
    path: k8s folder/Argocd
  destination:
    server: https://13.48.248.233:6443
    namespace: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
