apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-ip-app
  annotations:
    author: anand
    emailId: hello@gmail.com
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
      environment: prod
  template:
    metadata:
      labels:
        app: nginx
        environment: prod
    spec:
      containers:
        - name: ip-app
          image: harshajain/ip-app:latest
          ports:
            - containerPort: 80
